title: Boekhouding
modelClass: NielsVanDenDries\NielsVanDenDries\Models\Boekhouding
list: $/nielsvandendries/nielsvandendries/models/boekhouding/columns.yaml
recordUrl: 'nielsvandendries/nielsvandendries/boekhouding/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
showSorting: 0
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
